export interface BrandDNA {
  id: string;
  user_id: string;

  // Lightweight identity (generated in conversational onboarding)
  name: string;
  tagline: string;
  story: string;
  niche: string;
  target_audience: string;
  brand_values: string[];
  voice_tone: string;
  price_tier: "budget" | "mid" | "premium" | "luxury";
  palette: ColorPalette;
  typography: Typography;
  logo_url?: string;
  logo_prompt?: string;

  // Full Brand Book — generated in background after launch.
  // brand_book_status: "pending" | "generating" | "ready" | "failed"
  brand_book?: BrandBook;
  brand_book_status?: "pending" | "generating" | "ready" | "failed";

  // Public storefront identity
  slug?: string;
  storefront_config?: Record<string, unknown>;

  status: "draft" | "active";
  created_at: string;
  updated_at: string;
}

/**
 * Complete Brand Book — the source of truth for all future brand decisions.
 * Generated by the AI Brand Strategist after initial onboarding.
 *
 * Every AI-generated asset (product listings, designs, emails, social posts)
 * should reference this for consistency.
 */
export interface BrandBook {
  // ── Foundation ────────────────────────────────────────────
  alternative_names: string[];
  domain_suggestions: string[];
  brand_meaning: string;             // why the name works + emotional resonance

  // ── Strategy ──────────────────────────────────────────────
  mission: string;
  vision: string;
  brand_promise: string;

  // ── Customer Persona ─────────────────────────────────────
  persona: {
    age_range: string;
    gender_mix: string;
    location: string;
    income: string;
    interests: string[];
    buying_behavior: string;
    motivations: string;
    pain_points: string;
    aspirations: string;
  };

  // ── Personality & Archetype ───────────────────────────────
  personality_traits: { trait: string; how_it_shows: string }[];
  archetype: string;                 // Creator | Explorer | Hero | Rebel | Sage | Everyman | …
  archetype_reasoning: string;

  // ── Tone of Voice ─────────────────────────────────────────
  we_are: string[];                  // ["Confident", "Conversational"…]
  we_are_not: string[];              // ["Corporate", "Pushy"…]

  // ── Messaging ─────────────────────────────────────────────
  taglines: string[];
  headlines: string[];
  copy_examples: { instead_of: string; say: string }[];

  // ── Visual identity (detail) ──────────────────────────────
  palette_meanings: { color: string; hex: string; meaning: string }[];
  typography_detail: {
    headline_font: string;
    body_font: string;
    fallback_fonts: string;
    usage_rules: string;
  };
  visual_style: {
    photography: string;
    illustration: string;
    design_direction: string;
    mood: string;
  };

  // ── Brand guidelines ──────────────────────────────────────
  logo_usage_do: string[];
  logo_usage_dont: string[];
  approved_color_combos: string[];
  typography_hierarchy: string;
  social_visual_direction: string;

  // ── Product positioning ───────────────────────────────────
  core_categories: string[];
  hero_products: string[];
  future_expansion: string[];
  launch_collection: string[];

  // ── Pricing strategy ──────────────────────────────────────
  pricing_strategy: {
    entry_range: string;
    core_range: string;
    premium_range: string;
    reasoning: string;
  };

  // ── Competitive positioning ───────────────────────────────
  competitors: string[];
  why_choose_us: string;
  positioning_statement: string;

  // ── Packaging ─────────────────────────────────────────────
  packaging: {
    style: string;
    unboxing_experience: string;
    brand_inserts: string;
    thank_you_message: string;
    sticker_concepts: string;
  };

  // ── Social media playbook ─────────────────────────────────
  social: {
    instagram_bio: string;
    tiktok_bio: string;
    content_pillars: string[];
    posting_themes: string[];
    hashtags: string[];
  };

  // ── Email marketing foundation ────────────────────────────
  email_tones: {
    welcome: string;
    abandoned_cart: string;
    launch: string;
    support: string;
  };
}

export interface ColorPalette {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  text: string;
  [key: string]: string;
}

export interface Typography {
  heading: string;
  body: string;
  style: string;
}

/**
 * Product = the Digital Twin of a sellable item.
 * Every artifact (artwork, mockup, production file, lifestyle) derives from this.
 */
export interface Product {
  id: string;
  brand_id: string;
  name: string;
  description: string;
  category: string;

  // ── Supplier template binding ─────────────────────────────
  qikink_product_id: string;       // → ProductTemplate.id in catalog
  qikink_product_name: string;
  template_view: "front" | "back" | "side";

  // ── Pricing ───────────────────────────────────────────────
  base_cost: number;
  sell_price: number;

  // ── Digital twin assets ───────────────────────────────────
  design_prompt: string;            // creative prompt for AI artwork
  artwork_url?: string;             // standalone graphic (transparent bg)
  design_url?: string;              // legacy alias of artwork_url
  mockup_url?: string;              // template + artwork composited (catalog image)
  production_file_url?: string;     // print-ready PNG at print DPI
  placement?: {
    /** One of the 4 named placements (V1 catalog rule) — the starting box. */
    key: "front_center" | "back_center" | "front_pocket" | "full_back";
    /** Fine-tune within/around the placement box. Defaults: 1 / 0 / 0. */
    scale?: number;
    offset_x?: number;
    offset_y?: number;
  };
  /** Garment colors offered for this product (buyer picks one). */
  colors?: ("Black" | "White" | "Navy" | "Maroon")[];

  sku: string;
  variants: ProductVariant[];

  // ── Listing ───────────────────────────────────────────────
  listing_title: string;
  listing_description: string;
  seo_tags: string[];

  // ── New lifecycle / SEO fields ────────────────────────────
  discount_price?: number | null;
  url_slug?: string;
  meta_title?: string;
  meta_description?: string;
  tags?: string[];
  version?: number;
  published_at?: string | null;
  archived_at?: string | null;

  // PVE — visualization quality
  visualization_score?: number | null;
  validation_report?: Record<string, unknown>;

  // Lifecycle states per PRD. "active" kept for backward compat.
  status: "draft" | "published" | "archived" | "active";
  created_at: string;
}

/** Snapshot taken every time a product changes materially. */
export interface ProductVersion {
  id: string;
  product_id: string;
  version: number;
  snapshot: Partial<Product>;
  change_type: "create" | "edit" | "artwork" | "pricing" | "publish" | "unpublish" | "archive";
  change_summary?: string;
  created_at: string;
}

/** Append-only activity log per product. */
export interface ProductAuditEntry {
  id: string;
  product_id: string;
  user_id: string;
  action: string;
  details: Record<string, unknown>;
  created_at: string;
}

export interface ProductVariant {
  size?: string;
  color?: string;
  price: number;
  stock?: number;
}

export interface Order {
  id: string;
  brand_id: string;
  product_id: string;
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  shipping_address: ShippingAddress;
  variant: ProductVariant;
  quantity: number;
  total_amount: number;
  cost_amount: number;
  profit_amount: number;
  status: OrderStatus;
  qikink_order_id?: string;
  tracking_number?: string;
  courier?: string;
  created_at: string;
  updated_at: string;
}

export type OrderStatus =
  | "pending"
  | "confirmed"
  | "in_production"
  | "ready_to_ship"
  | "shipped"
  | "delivered"
  | "cancelled"
  | "refund_requested";

export interface ShippingAddress {
  line1: string;
  line2?: string;
  city: string;
  state: string;
  pincode: string;
  country: string;
}

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export interface OnboardingState {
  step: number;
  messages: ChatMessage[];
  brandDraft: Partial<BrandDNA>;
  isComplete: boolean;
}

// Re-export the canonical template type from the catalog module.
export type { ProductTemplate, ProductView, PlacementDef, PrintArea } from "./qikink-catalog";
